#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

WORK1=""
WORK2=""
WORK3=""
WORK4=""
WORK5=""
WORK6=""

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

bspc monitor -d "$WORK1" "$WORK2" "$WORK3" "$WORK4" "$WORK5" "$WORK6"

bspc config border_width          1
bspc config window_gap            12
bspc config focus_follows_pointer true
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc rule -a Roxterm state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a Evince desktop="^3"
bspc rule -a TelegramDesktop desktop="^4"

polybar mybar &
roxterm &
